// export const REGISTER_URL = 'http://localhost:1337/users/register'
// export const LOGIN_URL = 'http://localhost:1337/users/login'
// export const USERS_URL = 'http://localhost:1337/users'
export const CATEGORIES_URL = 'http://localhost:1337/categories';
export const PRODUCTS_URL = 'http://localhost:1337/products';
export const BRANDS_URL = 'http://localhost:1337/brands';
export const PRODUCTS_BY_CATEGORY_URL =
  'http://localhost:1337/products?category=';
export const PRODUCT_GET_BY_ID_URL = 'http://localhost:1337/products/';
// export const PRODUCT_PROMO_URL = 'http://localhost:1337/api/products/promo';
// export const PRODUCT_ARRAY_URL = 'http://localhost:1337/api/products/array=';
// export const PRODUCT_NEW_URL = 'http://localhost:1337/api/products/new';
// export const COMMENTS_PRODUCT_URL = 'http://localhost:1337/api/comments/';
// export const CREATE_COMMENT_URL = 'http://localhost:1337/api/comments';
// export const DELETE_COMMENT_URL =
//   'http://localhost:1337/api/comments/commentId=';
// export const UPDATE_COMMENT_URL = 'http://localhost:1337/api/comments/';
// export const CREATE_PRODUCT_URL = 'http://localhost:1337/api/products';
// export const UPDATE_PRODUCT_URL = 'http://localhost:1337/api/products';
